1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?

In [94]:
''' NumPy provides support for large, multi-dimensional arrays and matrices, 
along with a collection of mathematical functions to operate on these arrays efficiently.
Many other scientific computing and data analysis libraries,
such as Pandas, SciPy, and Scikit-learn,
are built on top of NumPy. It serves as the backbone for these libraries'''

'''Advantages:- 
NumPy is highly optimized for numerical operations. 
It uses pre-compiled C code, which makes array operations significantly faster than using Python lists.
NumPy arrays consume less memory compared to Python lists. 
This is because NumPy arrays are stored in contiguous blocks of memory,
which allows for efficient memory usage and faster access.
NumPy allows for vectorized operations, which means can perform element-wise operations on arrays without the need for explicit loops. 
This leads to more readable and concise code.
NumPy  integrates with other scientific computing libraries, making it easier to perform complex data analysis and machine learning tasks
'''
'''
NumPy provides a wide range of mathematical functions, including linear algebra, statistical operations, and random number generation, which are not available in standard Python.
With NumPy, can handle large datasets more efficiently, making it ideal for data analysis and machine learning applications.
NumPy arrays can be used as inputs and outputs for various other libraries, enhancing Python’s capabilities for numerical and scientific computing.
'''

'\nNumPy provides a wide range of mathematical functions, including linear algebra, statistical operations, and random number generation, which are not available in standard Python.\nWith NumPy, can handle large datasets more efficiently, making it ideal for data analysis and machine learning applications.\nNumPy arrays can be used as inputs and outputs for various other libraries, enhancing Python’s capabilities for numerical and scientific computing.\n'

2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?

In [97]:
''' np.mean() 
Computes the arithmetic mean of the array elements.
Not support Optional array of weights.
it is straightforward and used when you only need the simple mean.
'''

''' np.average() 
supports weights, allowing to compute a weighted average.
it is more versatile and can be used for weighted averages,
providing additional control with the weights parameter.
'''

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

mean_value = np.mean(arr)
print("Mean:", mean_value)  

average_value = np.average(arr)
print("Average:", average_value) 

weights = np.array([1, 2, 3, 4, 5])
weighted_average = np.average(arr, weights=weights)
print("Weighted Average:", weighted_average)  

""" np.mean for simple avarage or statistics calculation mean.
    np.average()  When we need to calculate a weighted average."""

Mean: 3.0
Average: 3.0
Weighted Average: 3.6666666666666665


' np.mean for simple avarage or statistics calculation mean.\n    np.average()  When we need to calculate a weighted average.'

3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.

In [100]:
"""
array can be reverced:-
by slicing 
by np.flip()
by np.flipud() and np.fliplr() for 2D arrays
"""


'\narray can be reverced:-\nby slicing \nby np.flip()\nby np.flipud() and np.fliplr() for 2D arrays\n'

In [102]:
''' 1D array'''
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]
print("Original array:", arr)  
print("Reversed array by slicing :", reversed_arr)  

r_arr = np.flip(arr)  
print("Reversed array by flip():", r_arr) 


Original array: [1 2 3 4 5]
Reversed array by slicing : [5 4 3 2 1]
Reversed array by flip(): [5 4 3 2 1]


In [104]:
''' 2D array '''
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_rows = arr[::-1, :]
print("Original array:\n", arr)
print("Reversed rows array by slicing :\n", reversed_rows)
reversed_columns = arr[:, ::-1]
print("Reversed columns array by slicing :\n", reversed_columns)

reversed_arrr = np.flip(arr, axis=0)
print("Reversed along axis 0 array by flip():\n", reversed_arrr)
reversed_arr = np.flip(arr, axis=1)
print("Reversed along axis 1 array by flip():\n", reversed_arrr)

reversed_arr = np.flipud(arr)
print("Flipped up-down array:\n", reversed_arr)
reversed_arr = np.fliplr(arr)
print("Flipped left-right array:\n", reversed_arr)

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed rows array by slicing :
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
Reversed columns array by slicing :
 [[3 2 1]
 [6 5 4]
 [9 8 7]]
Reversed along axis 0 array by flip():
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
Reversed along axis 1 array by flip():
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
Flipped up-down array:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
Flipped left-right array:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.

In [107]:
import numpy as np

arr_A = np.array([1, 2, 3, 4, 5], dtype='float32')
print(arr_A.dtype)

arr_B = np.array([1, 2, 3, 4, 5], dtype='float64')
print(arr_B.dtype)

arr_C = np.array(['1','2','3','4'])
print(arr_C, arr_C.dtype)

arr_C = np.array(['1','2','3','4'], dtype='int32' )
print(arr_C, arr_C.dtype)

'''Memory Management:-
Different data types require different amounts of memory.
For example, an int32 type uses 4 bytes, while an int64 type uses 8 bytes. 
Choosing the appropriate data type can save memory.'''

'''Performance Optimization:-
Operations on smaller data types are generally faster because they require less memory bandwidth 
and can be processed more quickly by the CPU.'''

float32
float64
['1' '2' '3' '4'] <U1
[1 2 3 4] int32


'Performance Optimization:-\nOperations on smaller data types are generally faster because they require less memory bandwidth \nand can be processed more quickly by the CPU.'

5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

In [110]:
"""An ndarray (N-dimensional array) is a core data structure in NumPy, 
designed for efficient numerical computations. 
It is a multi-dimensional, homogeneous array of fixed-size items, 
meaning all elements in the array must be of the same data type"""

"""key features:-
Provides a wide range of mathematical functions and operations.
Size is fixed upon creation.
Optimized for numerical operations, supporting vectorized operations and broadcasting.
Stored in contiguous memory blocks, leading to better memory efficiency.
All elements must be of the same data type."""

""" differ:-
List Can contain elements of different data types and multiple value(no fixed size). ndarry can't cantain
List Stored as arrays of pointers to objects, which can be less memory-efficient.
List Not optimized for numerical computations; operations often require explicit loops, but ndarray more efficient for it
"""
"""example"""
import numpy as np
#ndarray-------
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("ndarray:\n", arr)
print("Data type:", arr.dtype)
print("Shape:", arr.shape)

print("--------------------------------------------------------------")
#list------
lis= ['a','b',1,2,3]
print("list items:", lis)
list_2d = [[1, 2, 3], [4, 5, 6]]
print("Python List:\n", list_2d)


ndarray:
 [[1 2 3]
 [4 5 6]]
Data type: int32
Shape: (2, 3)
--------------------------------------------------------------
list items: ['a', 'b', 1, 2, 3]
Python List:
 [[1, 2, 3], [4, 5, 6]]


6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

In [113]:
""" list performance by using time module """
import time

large_list = list(range(1000000))

start_time = time.time()

result_list = [x + 1 for x in large_list]

end_time = time.time()

print("Time taken with Python list:", end_time - start_time)


Time taken with Python list: 0.03154349327087402


In [115]:
""" Numpy arrays performance by using time module  """
import numpy as np
import time

large_array = np.arange(1000000)

start_time = time.time()
result_array = large_array + 1
end_time = time.time()

print("Time taken with NumPy array:", end_time - start_time)


Time taken with NumPy array: 0.0009987354278564453


7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.

In [118]:
''' vstack:- 
Stacks arrays vertically (row-wise).
Arrays must have the same shape along all but the first axis.
use -  when need to stack arrays vertically, adding rows. '''
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

result = np.vstack((a, b))
print("vstack result:\n", result)


''' hstack:- 
Stacks arrays horizontally (column-wise).
use - when need to stack arrays horizontally, adding columns.
Arrays must have the same shape along all but the second axis.'''

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Using hstack
result = np.hstack((a, b))
print("hstack result:\n", result)


vstack result:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
hstack result:
 [1 2 3 4 5 6]


8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.

In [121]:
'''fliplr():-
Requires at least a 2D array
Flips the array left to right (horizontally)
Flips along the second axis
'''

'''flipud():-
Flips the array up to down (vertically)
Works with 1D and higher-dimensional arrays
Flips along the first axis (rows)
'''

'flipud():-\nFlips the array up to down (vertically)\nWorks with 1D and higher-dimensional arrays\nFlips along the first axis (rows)\n'

In [123]:
import numpy as np
# 1D----------
print("1D--------------")
arr = np.array([1, 2, 3])
flipped_ud = np.flipud(arr)
print("Original array:", arr)
print("Flipped up-down array:", flipped_ud)

#2d------------
print("2D--------------")
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
flipped_lr = np.fliplr(arr)
print("Original array:\n", arr)
print("Flipped left-right array:\n", flipped_lr)
flipped_ud = np.flipud(arr)
print("Flipped up-down array:\n", flipped_ud)

#3D---------------
print("3D--------------")
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
flipped_lr = np.fliplr(arr)
flipped_ud = np.flipud(arr)
print("Original array:\n", arr)
print("Flipped left-right array:\n", flipped_lr)
print("Flipped up-down array:\n", flipped_ud)


1D--------------
Original array: [1 2 3]
Flipped up-down array: [3 2 1]
2D--------------
Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flipped left-right array:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]
Flipped up-down array:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
3D--------------
Original array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Flipped left-right array:
 [[[3 4]
  [1 2]]

 [[7 8]
  [5 6]]]
Flipped up-down array:
 [[[5 6]
  [7 8]]

 [[1 2]
  [3 4]]]


9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

In [126]:
'''The array_split() method in NumPy is used to split an array into multiple sub-arrays.
It is similar to the split() method but with added flexibility for handling uneven splits.
Unlike split(), which requires the array to be divided into equal parts, array_split() allows for uneven splits.
This is useful when the array cannot be evenly divided by the specified number of splits
'''
'''
When the array length is not perfectly divisible by the number of splits,
array_split() handles the uneven division by creating sub-arrays of different sizes:
'''
import numpy as np

x = np.arange(9)
result = np.array_split(x, 4)
print(result)


[array([0, 1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?

In [129]:
'''
Vectorization refers to the process of performing operations on entire arrays rather than individual elements. 
This eliminates the need for explicit loops in Python, 
allowing operations to be executed in optimized C code, which is much faster
Enhances performance and code simplicity by eliminating explicit loops.
'''

import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

result_vectorized = a + b
         
print(result_vectorized)  



[ 6  8 10 12]


In [131]:
'''Broadcasting describes how NumPy handles arrays of different shapes during arithmetic operations.
It allows smaller arrays to be automatically expanded to match the shape of larger arrays, 
enabling element-wise operations without the need for explicit looping'''

import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
vector = np.array([10, 20, 30])

result = matrix + vector

print(result)


[[11 22 33]
 [14 25 36]]


In [133]:
"""
Vectorization improves performance and readability by leveraging efficient,
low-level implementations for array operations.

Broadcasting enables element-wise operations on arrays of different shapes 
by expanding dimensions as needed, making code more flexible and memory-efficient.
"""

'\nVectorization improves performance and readability by leveraging efficient,\nlow-level implementations for array operations.\n\nBroadcasting enables element-wise operations on arrays of different shapes \nby expanding dimensions as needed, making code more flexible and memory-efficient.\n'