## Assignment Numpy

### Theory

1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?

In [4]:
''' NumPy provides support for large, multi-dimensional arrays and matrices, 
along with a collection of mathematical functions to operate on these arrays efficiently.
Many other scientific computing and data analysis libraries,
such as Pandas, SciPy, and Scikit-learn,
are built on top of NumPy. It serves as the backbone for these libraries'''

'''Advantages:- 
NumPy is highly optimized for numerical operations. 
It uses pre-compiled C code, which makes array operations significantly faster than using Python lists.
NumPy arrays consume less memory compared to Python lists. 
This is because NumPy arrays are stored in contiguous blocks of memory,
which allows for efficient memory usage and faster access.
NumPy allows for vectorized operations, which means can perform element-wise operations on arrays without the need for explicit loops. 
This leads to more readable and concise code.
NumPy  integrates with other scientific computing libraries, making it easier to perform complex data analysis and machine learning tasks
'''
'''
NumPy provides a wide range of mathematical functions, including linear algebra, statistical operations, and random number generation, which are not available in standard Python.
With NumPy, can handle large datasets more efficiently, making it ideal for data analysis and machine learning applications.
NumPy arrays can be used as inputs and outputs for various other libraries, enhancing Python’s capabilities for numerical and scientific computing.
'''

'\nNumPy provides a wide range of mathematical functions, including linear algebra, statistical operations, and random number generation, which are not available in standard Python.\nWith NumPy, can handle large datasets more efficiently, making it ideal for data analysis and machine learning applications.\nNumPy arrays can be used as inputs and outputs for various other libraries, enhancing Python’s capabilities for numerical and scientific computing.\n'

2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?

In [6]:
''' np.mean() 
Computes the arithmetic mean of the array elements.
Not support Optional array of weights.
it is straightforward and used when you only need the simple mean.
'''

''' np.average() 
supports weights, allowing to compute a weighted average.
it is more versatile and can be used for weighted averages,
providing additional control with the weights parameter.
'''

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

mean_value = np.mean(arr)
print("Mean:", mean_value)  

average_value = np.average(arr)
print("Average:", average_value) 

weights = np.array([1, 2, 3, 4, 5])
weighted_average = np.average(arr, weights=weights)
print("Weighted Average:", weighted_average)  

""" np.mean for simple avarage or statistics calculation mean.
    np.average()  When we need to calculate a weighted average."""

Mean: 3.0
Average: 3.0
Weighted Average: 3.6666666666666665


' np.mean for simple avarage or statistics calculation mean.\n    np.average()  When we need to calculate a weighted average.'

3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.

In [8]:
"""
array can be reverced:-
by slicing 
by np.flip()
by np.flipud() and np.fliplr() for 2D arrays
"""


'\narray can be reverced:-\nby slicing \nby np.flip()\nby np.flipud() and np.fliplr() for 2D arrays\n'

In [9]:
''' 1D array'''
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]
print("Original array:", arr)  
print("Reversed array by slicing :", reversed_arr)  

r_arr = np.flip(arr)  
print("Reversed array by flip():", r_arr) 


Original array: [1 2 3 4 5]
Reversed array by slicing : [5 4 3 2 1]
Reversed array by flip(): [5 4 3 2 1]


In [10]:
''' 2D array '''
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_rows = arr[::-1, :]
print("Original array:\n", arr)
print("Reversed rows array by slicing :\n", reversed_rows)
reversed_columns = arr[:, ::-1]
print("Reversed columns array by slicing :\n", reversed_columns)

reversed_arrr = np.flip(arr, axis=0)
print("Reversed along axis 0 array by flip():\n", reversed_arrr)
reversed_arr = np.flip(arr, axis=1)
print("Reversed along axis 1 array by flip():\n", reversed_arrr)

reversed_arr = np.flipud(arr)
print("Flipped up-down array:\n", reversed_arr)
reversed_arr = np.fliplr(arr)
print("Flipped left-right array:\n", reversed_arr)

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed rows array by slicing :
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
Reversed columns array by slicing :
 [[3 2 1]
 [6 5 4]
 [9 8 7]]
Reversed along axis 0 array by flip():
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
Reversed along axis 1 array by flip():
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
Flipped up-down array:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
Flipped left-right array:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.

In [12]:
import numpy as np

arr_A = np.array([1, 2, 3, 4, 5], dtype='float32')
print(arr_A.dtype)

arr_B = np.array([1, 2, 3, 4, 5], dtype='float64')
print(arr_B.dtype)

arr_C = np.array(['1','2','3','4'])
print(arr_C, arr_C.dtype)

arr_C = np.array(['1','2','3','4'], dtype='int32' )
print(arr_C, arr_C.dtype)

'''Memory Management:-
Different data types require different amounts of memory.
For example, an int32 type uses 4 bytes, while an int64 type uses 8 bytes. 
Choosing the appropriate data type can save memory.'''

'''Performance Optimization:-
Operations on smaller data types are generally faster because they require less memory bandwidth 
and can be processed more quickly by the CPU.'''

float32
float64
['1' '2' '3' '4'] <U1
[1 2 3 4] int32


'Performance Optimization:-\nOperations on smaller data types are generally faster because they require less memory bandwidth \nand can be processed more quickly by the CPU.'

5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

In [14]:
"""An ndarray (N-dimensional array) is a core data structure in NumPy, 
designed for efficient numerical computations. 
It is a multi-dimensional, homogeneous array of fixed-size items, 
meaning all elements in the array must be of the same data type"""

"""key features:-
Provides a wide range of mathematical functions and operations.
Size is fixed upon creation.
Optimized for numerical operations, supporting vectorized operations and broadcasting.
Stored in contiguous memory blocks, leading to better memory efficiency.
All elements must be of the same data type."""

""" differ:-
List Can contain elements of different data types and multiple value(no fixed size). ndarry can't cantain
List Stored as arrays of pointers to objects, which can be less memory-efficient.
List Not optimized for numerical computations; operations often require explicit loops, but ndarray more efficient for it
"""
"""example"""
import numpy as np
#ndarray-------
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("ndarray:\n", arr)
print("Data type:", arr.dtype)
print("Shape:", arr.shape)

print("--------------------------------------------------------------")
#list------
lis= ['a','b',1,2,3]
print("list items:", lis)
list_2d = [[1, 2, 3], [4, 5, 6]]
print("Python List:\n", list_2d)


ndarray:
 [[1 2 3]
 [4 5 6]]
Data type: int32
Shape: (2, 3)
--------------------------------------------------------------
list items: ['a', 'b', 1, 2, 3]
Python List:
 [[1, 2, 3], [4, 5, 6]]


6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

In [16]:
""" list performance by using time module """
import time

large_list = list(range(1000000))

start_time = time.time()

result_list = [x + 1 for x in large_list]

end_time = time.time()

print("Time taken with Python list:", end_time - start_time)


Time taken with Python list: 0.03735041618347168


In [17]:
""" Numpy arrays performance by using time module  """
import numpy as np
import time

large_array = np.arange(1000000)

start_time = time.time()
result_array = large_array + 1
end_time = time.time()

print("Time taken with NumPy array:", end_time - start_time)


Time taken with NumPy array: 0.0011255741119384766


7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.

In [19]:
''' vstack:- 
Stacks arrays vertically (row-wise).
Arrays must have the same shape along all but the first axis.
use -  when need to stack arrays vertically, adding rows. '''
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

result = np.vstack((a, b))
print("vstack result:\n", result)


''' hstack:- 
Stacks arrays horizontally (column-wise).
use - when need to stack arrays horizontally, adding columns.
Arrays must have the same shape along all but the second axis.'''

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Using hstack
result = np.hstack((a, b))
print("hstack result:\n", result)


vstack result:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
hstack result:
 [1 2 3 4 5 6]


8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.

In [21]:
'''fliplr():-
Requires at least a 2D array
Flips the array left to right (horizontally)
Flips along the second axis
'''

'''flipud():-
Flips the array up to down (vertically)
Works with 1D and higher-dimensional arrays
Flips along the first axis (rows)
'''

'flipud():-\nFlips the array up to down (vertically)\nWorks with 1D and higher-dimensional arrays\nFlips along the first axis (rows)\n'

In [22]:
import numpy as np
# 1D----------
print("1D--------------")
arr = np.array([1, 2, 3])
flipped_ud = np.flipud(arr)
print("Original array:", arr)
print("Flipped up-down array:", flipped_ud)

#2d------------
print("2D--------------")
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
flipped_lr = np.fliplr(arr)
print("Original array:\n", arr)
print("Flipped left-right array:\n", flipped_lr)
flipped_ud = np.flipud(arr)
print("Flipped up-down array:\n", flipped_ud)

#3D---------------
print("3D--------------")
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
flipped_lr = np.fliplr(arr)
flipped_ud = np.flipud(arr)
print("Original array:\n", arr)
print("Flipped left-right array:\n", flipped_lr)
print("Flipped up-down array:\n", flipped_ud)


1D--------------
Original array: [1 2 3]
Flipped up-down array: [3 2 1]
2D--------------
Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flipped left-right array:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]
Flipped up-down array:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
3D--------------
Original array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Flipped left-right array:
 [[[3 4]
  [1 2]]

 [[7 8]
  [5 6]]]
Flipped up-down array:
 [[[5 6]
  [7 8]]

 [[1 2]
  [3 4]]]


9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

In [24]:
'''The array_split() method in NumPy is used to split an array into multiple sub-arrays.
It is similar to the split() method but with added flexibility for handling uneven splits.
Unlike split(), which requires the array to be divided into equal parts, array_split() allows for uneven splits.
This is useful when the array cannot be evenly divided by the specified number of splits
'''
'''
When the array length is not perfectly divisible by the number of splits,
array_split() handles the uneven division by creating sub-arrays of different sizes:
'''
import numpy as np

x = np.arange(9)
result = np.array_split(x, 4)
print(result)


[array([0, 1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?

In [26]:
'''
Vectorization refers to the process of performing operations on entire arrays rather than individual elements. 
This eliminates the need for explicit loops in Python, 
allowing operations to be executed in optimized C code, which is much faster
Enhances performance and code simplicity by eliminating explicit loops.
'''

import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

result_vectorized = a + b
         
print(result_vectorized)  



[ 6  8 10 12]


In [27]:
'''Broadcasting describes how NumPy handles arrays of different shapes during arithmetic operations.
It allows smaller arrays to be automatically expanded to match the shape of larger arrays, 
enabling element-wise operations without the need for explicit looping'''

import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
vector = np.array([10, 20, 30])

result = matrix + vector

print(result)


[[11 22 33]
 [14 25 36]]


In [28]:
"""
Vectorization improves performance and readability by leveraging efficient,
low-level implementations for array operations.

Broadcasting enables element-wise operations on arrays of different shapes 
by expanding dimensions as needed, making code more flexible and memory-efficient.
"""

'\nVectorization improves performance and readability by leveraging efficient,\nlow-level implementations for array operations.\n\nBroadcasting enables element-wise operations on arrays of different shapes \nby expanding dimensions as needed, making code more flexible and memory-efficient.\n'

## Practical 

1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [31]:
import numpy as np

array = np.random.randint(1, 101, size=(3, 3))
print("Original array:")
print(array)

transposed_array = array.T
print("\nTransposed array:")
print(transposed_array)


Original array:
[[77 46 59]
 [69 46 15]
 [50 45 77]]

Transposed array:
[[77 69 50]
 [46 46 45]
 [59 15 77]]


2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [33]:
array_1d = np.arange(10)
print("Original 1D array:")
print(array_1d)

array_2x5 = array_1d.reshape(2, 5)
print("\nReshaped to 2x5 array:")
print(array_2x5)

array_5x2 = array_2x5.reshape(5, 2)
print("\nReshaped to 5x2 array:")
print(array_5x2)


Original 1D array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped to 2x5 array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped to 5x2 array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [35]:
array_4x4 = np.random.rand(4, 4)
print("Original 4x4 array:")
print(array_4x4)

array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)
print("\n6x6 array with border of zeros:")
print(array_6x6)


Original 4x4 array:
[[0.34629128 0.85151664 0.85181985 0.28331981]
 [0.01877224 0.62279067 0.57430851 0.72492068]
 [0.25426326 0.8625452  0.34697895 0.54168828]
 [0.72112347 0.15302257 0.48203575 0.19679443]]

6x6 array with border of zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.34629128 0.85151664 0.85181985 0.28331981 0.        ]
 [0.         0.01877224 0.62279067 0.57430851 0.72492068 0.        ]
 [0.         0.25426326 0.8625452  0.34697895 0.54168828 0.        ]
 [0.         0.72112347 0.15302257 0.48203575 0.19679443 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [37]:
array = np.arange(10, 61, 5)

print("Array with integers from 10 to 60 with a step of 5:")
print(array)


Array with integers from 10 to 60 with a step of 5:
[10 15 20 25 30 35 40 45 50 55 60]


5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations

In [39]:
array = np.array(['python', 'numpy', 'pandas'])
print("Original array:")
print(array)

upper_array = np.char.upper(array)
print("\nUppercase array:")
print(upper_array)

lower_array = np.char.lower(array)
print("\nLowercase array:")
print(lower_array)

title_array = np.char.title(array)
print("\ntitle array:")
print(title_array)

capitalize_array = np.char.capitalize(array)
print("\nCapitalized array:")
print(capitalize_array)


Original array:
['python' 'numpy' 'pandas']

Uppercase array:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase array:
['python' 'numpy' 'pandas']

title array:
['Python' 'Numpy' 'Pandas']

Capitalized array:
['Python' 'Numpy' 'Pandas']


6. Generate a NumPy array of words. Insert a space between each character of every word in the array

In [41]:
words_array = np.array(['apple', 'ball ', 'cat'])
print("Original array:")
print(words_array)

spaced_array = np.char.join(' ', words_array)
print("\nArray with spaces between characters:")
print(spaced_array)


Original array:
['apple' 'ball ' 'cat']

Array with spaces between characters:
['a p p l e' 'b a l l  ' 'c a t']


7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [43]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)

addition = np.add(array1, array2)
print("\n addition:")
print(addition)

subtraction = np.subtract(array1, array2)
print("\n subtraction:")
print(subtraction)

multiplication = np.multiply(array1, array2)
print("\n multiplication:")
print(multiplication)

division = np.divide(array1, array2)
print("\n division:")
print(division)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

 addition:
[[ 8 10 12]
 [14 16 18]]

 subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

 multiplication:
[[ 7 16 27]
 [40 55 72]]

 division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [45]:
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:")
print(identity_matrix)

diagonal_elements = np.diag(identity_matrix)
print("\nDiagonal Elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.

In [47]:
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

random_array = np.random.randint(0, 1001, size=100)
print("Random array:")
print(random_array)

prime_numbers = [num for num in random_array if is_prime(num)]
print("\nPrime numbers in the array:")
print(prime_numbers)


Random array:
[364 488 988 207 250 278 469 174 994 694 970 426 727 560 799  33 234 497
 992 664 848 401 669 309 264 193 423 840 413 884 280 387 663 248 972 670
 286 912 314 268 293 536 208 243 624 890 664 884 828 452  34 333 666 584
 733 295 960  39 779  48 276 202 769 853 359 974 648 579 622 168 242 424
 974 512 166 760 334 999 370 106 693 360 560 834 853 673 736 475 775 266
  55 208 735 875  71 995 502 597 580 259]

Prime numbers in the array:
[727, 401, 193, 293, 733, 769, 853, 359, 853, 673, 71]


10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.

In [49]:
daily_temperatures = np.random.uniform(20, 40, 30)
print("Daily temperatures for a month:")
print(daily_temperatures)

weekly_averages = [np.mean(daily_temperatures[i:i+7]) for i in range(0, len(daily_temperatures), 7)]
print("\nWeekly averages:")
print(weekly_averages)


Daily temperatures for a month:
[22.07669576 23.63265575 35.81847383 22.51429352 26.568323   21.01317128
 36.32684361 27.30621452 38.63345696 33.3619863  25.56488134 31.34582014
 34.71382437 30.51790797 34.79574137 25.43192944 28.18790015 30.1328607
 24.91237079 25.51096    31.70455802 35.99336183 32.85793184 32.77379507
 36.30064059 32.39774108 26.07737748 35.05094998 33.83388698 29.09563674]

Weekly averages:
[26.850065251107765, 31.634870230050318, 28.66804578075411, 33.06454255299226, 31.464761860503103]
